---
title: "Problem Set 1 - My Answer"
author: 
  - Junjie LIU:
      email: liuj13@tcd.ie
      institute: [TCD-polisci]
      correspondence: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
institute:
  - TCD-polisci: Department of Political Science, Trinity College Dublin, 2 Clare, Street, Dublin 2, Ireland
toc: false
output:
  bookdown::pdf_document2:
    includes:
      in_header: dependency.sty
    pandoc_args:
      - --lua-filter=../../../environment/scholarly-metadata.lua
      - --lua-filter=../../../environment/author-info-blocks.lua
---

\section*{Instructions}
\begin{itemize}
	\item Please show your work! You may lose points by simply writing in the answer. If the problem requires you to execute commands in \texttt{R}, please include the code you used to get your answers. Please also include the \texttt{.R} file that contains your code. If you are not sure if work needs to be shown for a particular problem, please ask.
	\item Your homework should be submitted electronically on GitHub in \texttt{.pdf} form.
	\item This problem set is due before 23:59 on Sunday February 18, 2024. No late assignments will be accepted.
 	\item Total available points for this homework is 80.
\end{itemize}

	
\noindent In this problem set, you will run several regressions and create an add variable plot (see the lecture slides) in \texttt{R} using the \texttt{incumbents\_subset.csv} dataset. Include all of your code.

\vspace{.25cm}
\section*{Question 1} %(20 points)}
\vspace{.25cm}
\noindent We're interested in what types of international environmental agreements or policies people support (\href{https://www.pnas.org/content/110/34/13763}{Bechtel and Scheve 2013)}. So, we asked 8,500 individuals whether they support a given policy, and for each participant, we vary the (1) number of countries that participate in the international agreement and (2) sanctions for not following the agreement. \\

\noindent Load in the data labeled \texttt{climateSupport.RData} on GitHub, which contains an observational study of 8,500 observations.

\begin{itemize}
	\item
	Response variable: 
	\begin{itemize}
		\item \texttt{choice}: 1 if the individual agreed with the policy; 0 if the individual did not support the policy
	\end{itemize}
	\item
	Explanatory variables: 
	\begin{itemize}
		\item
		\texttt{countries}: Number of participating countries [20 of 192; 80 of 192; 160 of 192]
		\item
		\texttt{sanctions}: Sanctions for missing emission reduction targets [None, 5\%, 15\%, and 20\% of the monthly household costs given 2\% GDP growth]
		
	\end{itemize}
	
\end{itemize}

\newpage
\noindent Please answer the following questions:

\begin{enumerate}
	\item
	Remember, we are interested in predicting the likelihood of an individual supporting a policy based on the number of countries participating and the possible sanctions for non-compliance.
	\begin{enumerate}
		\item [] Fit an additive model. Provide the summary output, the global null hypothesis, and $p$-value. Please describe the results and provide a conclusion.
		%\item
		%How many iterations did it take to find the maximum likelihood estimates?
	\end{enumerate}
	
	\item
	If any of the explanatory variables are significant in this model, then:
	\begin{enumerate}
		\item
		For the policy in which nearly all countries participate [160 of 192], how does increasing sanctions from 5\% to 15\% change the odds that an individual will support the policy? (Interpretation of a coefficient)
%		\item
%		For the policy in which very few countries participate [20 of 192], how does increasing sanctions from 5\% to 15\% change the odds that an individual will support the policy? (Interpretation of a coefficient)
		\item
		What is the estimated probability that an individual will support a policy if there are 80 of 192 countries participating with no sanctions? 
		\item
		Would the answers to 2a and 2b potentially change if we included the interaction term in this model? Why? 
		\begin{itemize}
			\item Perform a test to see if including an interaction is appropriate.
		\end{itemize}
	\end{enumerate}
\end{enumerate}

\section*{\textcolor{My Answer}}

```{R}
# load data
library("fastDummies")
library("stringr")
load("../../../datasets/climateSupport.RData")
data <- climateSupport
head(data)

## preprocessing
data_dup <- data
data_dup$choice <- ifelse(data_dup$choice == "Not supported", 0, 1)
data_dup <-  fastDummies::dummy_columns(data_dup, 
                      select_columns = c("countries", "sanctions"), 
                      remove_first_dummy=TRUE, remove_selected_columns=TRUE)
names(data_dup) <- str_replace_all(names(data_dup), c(" " = "." , "," = "", "%" = ""))
head(data_dup)
```

```{R}
# Question 1
## modelling - additive model
model <- glm(as.formula(paste(names(data_dup)[1], "~", 
                        paste(names(data_dup)[-1], collapse = "+"))), 
             family=binomial(link="logit"), data=data_dup)

summary(model)
```


```{R}
# Question 2
print("The model's summary suggests that if almost every country is 
      involved in a policy (participate [160 of 192]), increasing the 
      penalty rate from 5% to 15% results in the reduction of the likelihood, 
      expressed in log odds, that a person will endorse the policy by 
      approximately 0.32511 (= -0.13325 - 0.19186).")

given_cond <- data.frame(
  countries_80.of.192=1, countries_160.of.192=0,
  sanctions_5 =0, sanctions_15=0, sanctions_20=0
)
prediction <- predict(model, given_cond, type="response")
print(paste("The prediction result is: ", round(prediction[1], 4)))


model_inter <- glm(choice~.*., family=binomial(link="logit"), data=data_dup)
summary(model_inter)
lr_test <- anova(model, model_inter, test="LRT")
print(lr_test)

print("the p-value of the likelihood ratio test is higher than the given 
      threshold: 0.05, thus, we could not reject the null hypothesis, and 
      there is no significant difference between the additive model and 
      model with interaction")
```

