---
title: "Problem Set 1 - My Answer"
author: 
  - Junjie LIU:
      email: liuj13@tcd.ie
      institute: [TCD-polisci]
      correspondence: true
date: "`r format(Sys.time(), '%d %B, %Y')`"
institute:
  - TCD-polisci: Department of Political Science, Trinity College Dublin, 2 Clare, Street, Dublin 2, Ireland
toc: false
output:
  bookdown::pdf_document2:
    includes:
      in_header: dependency.sty
    pandoc_args:
      - --lua-filter=../../../environment/scholarly-metadata.lua
      - --lua-filter=../../../environment/author-info-blocks.lua
---

\section*{Instructions}
\begin{itemize}
	\item Please show your work! You may lose points by simply writing in the answer. If the problem requires you to execute commands in \texttt{R}, please include the code you used to get your answers. Please also include the   \texttt{.R} file that contains your code. If you are not sure if work needs to be shown for a particular problem, please ask.
  \item Your homework should be submitted electronically on GitHub in \texttt{.pdf} form.
  \item This problem set is due before 23:59 on Sunday February 11, 2024. No late assignments will be accepted.
\end{itemize}

\section*{Question 1} 
\vspace{.25cm}
\noindent The Kolmogorov-Smirnov test uses cumulative distribution statistics test the similarity of the empirical distribution of some observed data and a specified PDF, and serves as a goodness of fit test. The test statistic is created by:

$$D = \max_{i=1:n} \Big\{ \frac{i}{n}  - F_{(i)}, F_{(i)} - \frac{i-1}{n} \Big\}$$

\noindent where $F$ is the theoretical cumulative distribution of the distribution being tested and $F_{(i)}$ is the $i$th ordered value. Intuitively, the statistic takes the largest absolute difference between the two distribution functions across all $x$ values. Large values indicate dissimilarity and the rejection of the hypothesis that the empirical distribution matches the queried theoretical distribution. The p-value is calculated from the Kolmogorov-
Smirnoff CDF:

$$p(D \leq d)= \frac{\sqrt {2\pi}}{d} \sum _{k=1}^{\infty }e^{-(2k-1)^{2}\pi ^{2}/(8d^{2})}$$


\noindent which generally requires approximation methods (see \href{https://core.ac.uk/download/pdf/25787785.pdf}{Marsaglia, Tsang, and Wang 2003}). This so-called non-parametric test (this label comes from the fact that the distribution of the test statistic does not depend on the distribution of the data being tested) performs poorly in small samples, but works well in a simulation environment. Write an \texttt{R} function that implements this test where the reference distribution is normal. Using \texttt{R} generate 1,000 Cauchy random variables (\texttt{rcauchy(1000, location = 0, scale = 1)}) and perform the test (remember, use the same seed, something like \texttt{set.seed(123)}, whenever you're generating your own data).
	
	
\noindent As a hint, you can create the empirical distribution and theoretical CDF using this code:

\begin{lstlisting}[language=R]
	# create empirical distribution of observed data
	ECDF <- ecdf(data)
	empiricalCDF <- ECDF(data)
	# generate test statistic
	D <- max(abs(empiricalCDF - pnorm(data))) 
\end{lstlisting}

\section*{\textcolor{blue}{Answer of Question 1}}

```{R}
ks_test_normal <- function(data) {
  empiricalCDF <- ecdf(data)
  D <- max(abs(empiricalCDF(data) - pnorm(data, 0, 1))) # std normal
  n <- length(data)
  p.value <- sqrt(2 * pi) / D * 
            sum(sapply(1:10000, function(k) exp(-((2 * k - 1)^2) * pi^2 / (8 * D^2))))
  ks_builtin <- ks.test(data, "pnorm", 0, 1) 
  list(D = D, p_value = p.value, builtins=ks_builtin) # includes the builtin function ks.test
}

set.seed(123)

data <- rcauchy(1000, location = 0, scale = 1)
ks_result <- ks_test_normal(data)
print(ks_result)
```
The results shows that the generated data does not follow normal distribution.

\section*{Question 2}
\noindent Estimate an OLS regression in \texttt{R} that uses the Newton-Raphson algorithm (specifically \texttt{BFGS}, which is a quasi-Newton method), and show that you get the equivalent results to using \texttt{lm}. Use the code below to create your data.
\vspace{.5cm}
\lstinputlisting[language=R, firstline=51,lastline=53]{PS1.R} 

\section*{\textcolor{blue}{Answer of Question 2}}

```{R}
set.seed(123)
data <- data.frame(x = runif(200, 1, 10))
data$y <- 0 + 2.75*data$x + rnorm(200, 0, 1.5)

criterion <- function(params, data) {
  with(data, sum((y - (params[1] + params[2] * x))^2))
}

init_params <- c(intercept = 0, slope = 0)
bfgs_results <- optim(par = init_params, fn = criterion, data = data, method = "BFGS")

bfgs_estimates <- bfgs_results$par
lm_results <- lm(y ~ x, data = data)

print(bfgs_estimates)
print(summary(lm_results)$coefficients)

paste0("While thie init is:", "(", init_params[1], init_params[2], "),", " the difference between LS and BFGS in intercept: ", bfgs_estimates[1] - summary(lm_results)$coefficients[1, 1])
paste0("While thie init is:", "(", init_params[1], init_params[2], "),", " the difference between LS and BFGS in slope: ", bfgs_estimates[2] - summary(lm_results)$coefficients[2, 1])
```
